import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const testVaultPluginDir = join("test-vault", ".obsidian", "plugins", "calendar-bases");

// Plugin to copy build artifacts to test vault
const copyToTestVault = {
	name: "copy-to-test-vault",
	setup(build) {
		build.onEnd(() => {
			if (prod || !existsSync(testVaultPluginDir)) return;
			const filesToCopy = ["main.js", "manifest.json", "styles.css"];
			for (const file of filesToCopy) {
				if (existsSync(file)) {
					copyFileSync(file, join(testVaultPluginDir, file));
				}
			}
			console.log("Copied build artifacts to test vault");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: prod ? [] : [copyToTestVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
